import * as XLSX from 'xlsx';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { parseOrder } from './import-parser.js';

const STAGES = ['COMPRA TECIDO/RISCO','ENFESTO/CORTE','ETIQUETAGEM/SEP.BORDADO','BORDADO/PERSONALIZAÇÃO','COSTURA','ACAB./PASSADORIA','EMBALAGEM'];
const PERMS = {
  VER_DADOS:['ADMIN','PCP','PRODUCAO','CONSULTA'], IMPORTAR_PEDIDO:['ADMIN'], EDITAR_ETAPA:['ADMIN','PCP','PRODUCAO'],
  EDITAR_PEDIDO:['ADMIN','PCP'], APAGAR_PEDIDO:['ADMIN'], GERENCIAR_USUARIOS:['ADMIN'], ALTERAR_QUALQUER_ETAPA:['ADMIN','PCP']
};
const env = name => { const value=process.env[name]; if(!value) throw new Error(`Variável ausente: ${name}`); return value; };
const sbHeaders = key => ({ apikey:key, Authorization:`Bearer ${key}`, 'Content-Type':'application/json' });
async function sb(method,path,payload,prefer='return=representation') {
  const key=env('SUPABASE_SERVICE_ROLE_KEY');
  const response=await fetch(`${env('SUPABASE_URL')}/rest/v1/${path}`,{method,headers:{...sbHeaders(key),Prefer:prefer},body:payload==null?undefined:JSON.stringify(payload)});
  const text=await response.text(); if(!response.ok) throw new Error(`Supabase ${response.status}: ${text}`); return text?JSON.parse(text):null;
}
const get=(table,q='')=>sb('GET',`${table}${q?'?'+q:''}`,null);
const post=(table,p,prefer)=>sb('POST',table,p,prefer);
const patch=(table,q,p,prefer)=>sb('PATCH',`${table}?${q}`,p,prefer);
const del=(table,q)=>sb('DELETE',`${table}?${q}`,null,'return=minimal');
const rpc=(name,payload)=>sb('POST',`rpc/${name}`,payload);
const eq=v=>`eq.${encodeURIComponent(String(v))}`;
const tokenOf=a=>a?.accessToken||a?.auth?.accessToken||a?.auth?.auth?.accessToken||'';
async function currentUser(auth, permission='VER_DADOS') {
  const token=tokenOf(auth); if(!token) throw new Error('Sessão expirada. Faça login novamente.');
  const response=await fetch(`${env('SUPABASE_URL')}/auth/v1/user`,{headers:sbHeaders(env('SUPABASE_PUBLISHABLE_KEY')).Authorization?{apikey:env('SUPABASE_PUBLISHABLE_KEY'),Authorization:`Bearer ${token}`}:{}});
  if(!response.ok) throw new Error('Sessão inválida ou expirada.');
  const authUser=await response.json(); const email=String(authUser.email||'').toLowerCase();
  let profiles=await get('usuarios_perfis',`select=*&or=(auth_user_id.eq.${authUser.id},email.eq.${encodeURIComponent(email)})&limit=1`);
  if(!profiles.length) {
    const any=await get('usuarios_perfis','select=id&limit=1');
    if(any.length) throw new Error('Usuário sem perfil autorizado.');
    profiles=await post('usuarios_perfis',{auth_user_id:authUser.id,email,nome:authUser.user_metadata?.name||email,perfil:'ADMIN',ativo:true});
  }
  const profile=profiles[0]; if(!profile.ativo) throw new Error('Usuário inativo.');
  const user={authUserId:authUser.id,email,nome:profile.nome||email,perfil:String(profile.perfil).toUpperCase(),ativo:true,usuarioPerfilId:profile.id};
  if(!(PERMS[permission]||[]).includes(user.perfil)) throw new Error(`Sem permissão: ${permission}.`);
  return user;
}
const permissions=profile=>Object.fromEntries(Object.entries(PERMS).map(([k,v])=>[k,v.includes(profile)]));
const isoBR=value=>value&&/^\d{4}-\d{2}-\d{2}/.test(value)?`${value.slice(8,10)}/${value.slice(5,7)}/${value.slice(0,4)}`:'';
const brISO=value=>{ const m=String(value||'').match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/); return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:(/^\d{4}-\d{2}-\d{2}$/.test(value)?value:null); };
const days=(a,b=new Date())=>a?Math.max(0,Math.floor((new Date(b)-new Date(`${a}T00:00:00`))/86400000)):'';
const normOrder=p=>({id:p.id,idPedido:p.id_pedido,numeroPedido:p.numero_pedido,numeroCorte:p.numero_corte||'',dataEntrada:isoBR(p.data_entrada),cliente:p.cliente,prazoOriginal:p.prazo_original||'',prazoMin:p.prazo_min||0,prazoMax:p.prazo_max||0,dataEntrega:isoBR(p.data_entrega),dataEntregaISO:p.data_entrega,qtdItens:p.qtd_itens||0,qtdTotal:Number(p.qtd_total||0),linkPdf:p.link_pdf||'',dataImportacao:p.data_importacao||'',usuario:p.usuario||'',status:p.status||''});
const normStage=e=>({id:e.id,idEtapa:e.id_etapa,idPedido:e.id_pedido,numeroPedido:e.numero_pedido,cliente:e.cliente,etapa:e.etapa,ordemEtapa:e.ordem_etapa,dataInicio:isoBR(e.data_inicio),dataConclusao:isoBR(e.data_conclusao),dataInicioISO:e.data_inicio,dataConclusaoISO:e.data_conclusao,responsavel:e.responsavel||'',tipoResponsavel:e.tipo_responsavel||'',observacao:e.observacao||'',costuraExterna:Boolean(e.costura_externa),statusEtapa:e.status_etapa||'PENDENTE',diasEmAberto:days(e.data_inicio,e.data_conclusao||new Date()),dataAtualizacao:e.data_atualizacao||'',usuarioAtualizacao:e.usuario_atualizacao||''});
function stageNow(stages) { const sorted=[...stages].sort((a,b)=>a.ordemEtapa-b.ordemEtapa); const open=sorted.find(x=>x.statusEtapa==='EM ANDAMENTO')||sorted.find(x=>x.statusEtapa!=='CONCLUÍDA'); return open?{etapa:open.etapa,ordem:open.ordemEtapa,status:open.statusEtapa,etapaObj:open}:{etapa:'CONCLUÍDO',ordem:99,status:'CONCLUÍDO',etapaObj:null}; }
function card(order, rawStages) { const stages=rawStages.map(normStage), now=stageNow(stages), open=now.etapaObj; const delivery=order.data_entrega?Math.floor((new Date(`${order.data_entrega}T00:00:00`)-new Date(new Date().toDateString()))/86400000):''; const stopped=open?days(open.dataInicioISO,open.dataConclusaoISO||new Date()):0; return {idPedidoDb:order.id,idPedido:order.id_pedido,numeroPedido:order.numero_pedido,numeroCorte:order.numero_corte||'',cliente:order.cliente,qtdTotal:Number(order.qtd_total||0),dataEntrada:isoBR(order.data_entrada),dataEntrega:isoBR(order.data_entrega),diasParaEntrega:delivery,etapaAtual:now.etapa,ordemEtapaAtual:now.ordem,statusEtapaAtual:now.status,costuraExterna:Boolean(open?.costuraExterna),concluido:now.etapa==='CONCLUÍDO',idEtapaAtual:open?.idEtapa||'',idEtapaDbAtual:open?.id||'',responsavelAtual:open?.responsavel||'',dataInicioAtual:open?.dataInicio||'',dataConclusaoAtual:open?.dataConclusao||'',observacaoAtual:open?.observacao||'',diasParado:stopped,cor:now.etapa==='CONCLUÍDO'?'done':delivery!==''&&delivery<0?'danger':stopped>=3||delivery!==''&&delivery<=15?'warning':'ok',linkPdf:order.link_pdf||''}; }
async function initial(auth) {
  const user=await currentUser(auth); const [orders,rawStages]=await Promise.all([get('pedidos','select=*&or=(ativo.eq.true,ativo.is.null)&order=numero_pedido.desc'),get('pedidos_etapas','select=*&order=numero_pedido.desc,ordem_etapa.asc')]);
  const cards=orders.map(o=>card(o,rawStages.filter(e=>String(e.numero_pedido)===String(o.numero_pedido)))); const columns=[...STAGES,'CONCLUÍDO'].map((etapa,i)=>({ordem:i+1,etapa,cards:cards.filter(c=>c.etapaAtual===etapa)}));
  const enriched=orders.map(normOrder).map(o=>({...o,...((({numeroPedido,cliente,qtdTotal,dataEntrada,dataEntrega,linkPdf,...rest})=>rest)(cards.find(c=>c.numeroPedido===o.numeroPedido)||{}))}));
  const active=cards.filter(c=>!c.concluido); return {appName:'ZANELLI | CENTRAL DE PEDIDOS',version:'7.0.0 - WEB',pedidos:enriched,recentes:enriched.slice(0,6),etapas:rawStages.map(normStage),kanban:{columns,colunas:columns,cards},metricas:{totalPedidos:orders.length,qtdTotal:active.reduce((s,c)=>s+c.qtdTotal,0),atrasados:active.filter(c=>c.diasParaEntrega!==''&&c.diasParaEntrega<0).length,pedidosParados:active.filter(c=>c.diasParado>=3).length},gargalos:columns.map(x=>({etapa:x.etapa,quantidade:x.cards.length,parados:x.cards.filter(c=>c.diasParado>=3).length,atrasados:x.cards.filter(c=>c.diasParaEntrega!==''&&c.diasParaEntrega<0).length})),usuario:user,permissoes:permissions(user.perfil)};
}
async function login(payload) { const response=await fetch(`${env('SUPABASE_URL')}/auth/v1/token?grant_type=password`,{method:'POST',headers:sbHeaders(env('SUPABASE_PUBLISHABLE_KEY')),body:JSON.stringify({email:payload.email,password:payload.senha})}); const data=await response.json(); if(!response.ok) throw new Error(data.msg||data.error_description||'Falha no login.'); const info=await currentUser({accessToken:data.access_token}); return {sucesso:true,accessToken:data.access_token,refreshToken:data.refresh_token||'',expiresIn:data.expires_in||3600,email:payload.email,usuario:info,permissoes:permissions(info.perfil)}; }
async function googleToken(){const body=new URLSearchParams({client_id:env('GOOGLE_CLIENT_ID'),client_secret:env('GOOGLE_CLIENT_SECRET'),refresh_token:env('GOOGLE_REFRESH_TOKEN'),grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const d=await r.json();if(!r.ok)throw new Error(`Google OAuth: ${d.error_description||d.error}`);return d.access_token;}
async function uploadPdf(bytes,name){const token=await googleToken(),boundary='zanelli_'+Date.now();const meta=JSON.stringify({name,parents:[env('GOOGLE_DRIVE_FOLDER_ID')]});const body=Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${meta}\r\n--${boundary}\r\nContent-Type: application/pdf\r\n\r\n`),Buffer.from(bytes),Buffer.from(`\r\n--${boundary}--`)]);const r=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,webViewLink',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':`multipart/related; boundary=${boundary}`},body});const d=await r.json();if(!r.ok)throw new Error(`Google Drive: ${d.error?.message||r.status}`);return d;}
async function analyze(payload){await currentUser(payload.auth,'IMPORTAR_PEDIDO');const buffer=Buffer.from(payload.base64,'base64');if(buffer.length>4_000_000)throw new Error('Na versão web, o Excel deve ter no máximo 4 MB.');const wb=XLSX.read(buffer,{cellDates:true}),ws=wb.Sheets[wb.SheetNames.find(n=>n.toUpperCase()==='PEDIDO')||wb.SheetNames[0]];const rawRows=XLSX.utils.sheet_to_json(ws,{header:1,raw:true,defval:''}),shownRows=XLSX.utils.sheet_to_json(ws,{header:1,raw:false,defval:''});const parsed=parseOrder(rawRows,shownRows,payload.nomeArquivo);const pdf=await PDFDocument.create(),page=pdf.addPage([842,595]),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);page.drawText(`PEDIDO ${parsed.numeroPedido}`,{x:45,y:535,size:20,font:bold,color:rgb(.08,.25,.16)});page.drawText(`Cliente: ${parsed.cliente}`.slice(0,110),{x:45,y:505,size:12,font});page.drawText(`Data: ${parsed.dataEntrada}   Prazo: ${parsed.prazoOriginal}`.slice(0,110),{x:45,y:483,size:11,font});page.drawText('Item',{x:45,y:455,size:10,font:bold});page.drawText('Manga / Tecido / Cor',{x:410,y:455,size:10,font:bold});page.drawText('Qtd.',{x:740,y:455,size:10,font:bold});let y=435;for(const item of parsed.itens.slice(0,22)){page.drawText(String(item.item).slice(0,62),{x:45,y,size:9,font});page.drawText(`${item.manga||'-'} / ${item.tecido||'-'} / ${item.cor||'-'}`.slice(0,52),{x:410,y,size:9,font});page.drawText(String(item.qtd),{x:740,y,size:9,font:bold});y-=17;}const uploaded=await uploadPdf(await pdf.save(),`TMP_PEDIDO_${parsed.numeroPedido||Date.now()}.pdf`);return{...parsed,tempPdfId:uploaded.id,nomePdfGerado:`PEDIDO ${parsed.numeroPedido}.pdf`,pdfGerado:true};}
async function audit(user,acao,tabela,id,numero,antes,depois,obs=''){try{await post('auditoria',{auth_user_id:user.authUserId,usuario_email:user.email,usuario_nome:user.nome,perfil:user.perfil,acao,tabela,registro_id:String(id||''),numero_pedido:String(numero||''),antes_json:antes,depois_json:depois,observacao:obs},'return=minimal');}catch(e){console.error(e);}}
async function driveFinalize(id,name){const token=await googleToken();const r=await fetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?fields=id,webViewLink`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({name})});const d=await r.json();if(!r.ok)throw new Error(`Google Drive: ${d.error?.message||r.status}`);return d;}
async function saveOrder(p){const user=await currentUser(p.auth,'IMPORTAR_PEDIDO'),number=String(p.numeroPedido||'').trim(),items=p.itens||[];if(!number||!p.cliente||!brISO(p.dataEntrada)||!Number(p.prazoMax)||!items.length||!p.tempPdfId)throw new Error('Revise número, cliente, data, prazo, itens e PDF.');const found=(await get('pedidos',`select=*&numero_pedido=${eq(number)}&limit=1`))[0];if(found&&!p.atualizarExistente)return{sucesso:false,duplicado:true,mensagem:`O pedido ${number} já está cadastrado. Deseja atualizar?`};const start=new Date(`${brISO(p.dataEntrada)}T12:00:00`);start.setDate(start.getDate()+Number(p.prazoMax));const pdf=await driveFinalize(p.tempPdfId,`PEDIDO ${number} - ${String(p.cliente).replace(/[\\/:*?"<>|#%]/g,'-')}.pdf`);const data={id_pedido:number,numero_pedido:number,data_entrada:brISO(p.dataEntrada),cliente:String(p.cliente).trim(),prazo_original:String(p.prazoOriginal||''),prazo_min:Number(p.prazoMin||p.prazoMax),prazo_max:Number(p.prazoMax),data_entrega:start.toISOString().slice(0,10),qtd_itens:items.length,qtd_total:items.reduce((s,x)=>s+Number(x.qtd||0),0),link_pdf:pdf.webViewLink,data_importacao:new Date().toISOString(),usuario:user.email,status:'IMPORTADO'};const safeItems=items.map((x,i)=>({item:String(x.item||'').trim(),manga:String(x.manga||''),tecido:String(x.tecido||''),cor:String(x.cor||''),qtd:Number(x.qtd||0),ordem_item:i+1,observacao:String(x.observacao||'')}));const order=await rpc('importar_pedido_atomico',{p_pedido:data,p_itens:safeItems,p_etapas:STAGES.map((etapa,i)=>({etapa,ordem_etapa:i+1}))});await audit(user,found?'ATUALIZAR_PEDIDO':'IMPORTAR_PEDIDO','pedidos',order.id,number,found||null,order);return{...(await initial(p.auth)),mensagem:`Pedido ${number} salvo com sucesso.`};}
async function quickStage(p,any=false){const permission=any?'ALTERAR_QUALQUER_ETAPA':'EDITAR_ETAPA',user=await currentUser(p.auth,permission),input=any?(p.etapa||{}):p,id=input.id||p.idEtapaDb,before=(await get('pedidos_etapas',`select=*&id=${eq(id)}&limit=1`))[0];if(!before)throw new Error('Etapa não encontrada.');const all=(await get('pedidos_etapas',`select=*&numero_pedido=${eq(before.numero_pedido)}&order=ordem_etapa.asc`)).map(normStage),now=stageNow(all);if(!any&&user.perfil==='PRODUCAO'&&String(now.etapaObj?.id)!==String(id))throw new Error('Produção pode alterar somente a etapa atual.');if(Number(before.ordem_etapa)===1&&user.perfil!=='ADMIN')throw new Error('COMPRA TECIDO/RISCO é exclusiva de ADMIN.');let begin=brISO(input.dataInicio),end=brISO(input.dataConclusao);if(!any&&p.concluir){begin=begin||new Date().toISOString().slice(0,10);end=end||new Date().toISOString().slice(0,10);}if(input.dataInicio&&!begin||input.dataConclusao&&!end)throw new Error('Data inválida.');if(begin&&end&&end<begin)throw new Error('Conclusão anterior ao início.');const updated=(await patch('pedidos_etapas',`id=${eq(id)}`,{data_inicio:begin,data_conclusao:end,responsavel:String(input.responsavel||'').trim(),observacao:String(input.observacao||'').trim(),costura_externa:before.etapa==='COSTURA'?Boolean(input.costuraExterna):false,status_etapa:end?'CONCLUÍDA':begin?'EM ANDAMENTO':'PENDENTE',dias_em_aberto:begin?days(begin,end||new Date()):null,data_atualizacao:new Date().toISOString(),usuario_atualizacao:user.email}))[0];if(Number(before.ordem_etapa)===1){const cut=String(input.numeroCorte||p.numeroCorte||'').trim();if(!cut)throw new Error('Informe o Nº CORTE.');await patch('pedidos',`numero_pedido=${eq(before.numero_pedido)}`,{numero_corte:cut},'return=minimal');}await audit(user,any?'EDITAR_QUALQUER_ETAPA':'EDITAR_ETAPA','pedidos_etapas',id,before.numero_pedido,before,updated);const order=(await get('pedidos',`select=*&numero_pedido=${eq(before.numero_pedido)}&limit=1`))[0],stages=await get('pedidos_etapas',`select=*&numero_pedido=${eq(before.numero_pedido)}`);return{sucesso:true,mensagem:'Etapa salva com sucesso.',etapa:normStage(updated),card:card(order,stages)};}
async function detail(p){await currentUser(p.auth);const order=(await get('pedidos',`select=*&numero_pedido=${eq(p.numeroPedido)}&limit=1`))[0];if(!order)throw new Error('Pedido não encontrado.');const [stages,items]=await Promise.all([get('pedidos_etapas',`select=*&numero_pedido=${eq(p.numeroPedido)}&order=ordem_etapa.asc`),get('pedidos_itens',`select=*&numero_pedido=${eq(p.numeroPedido)}&order=ordem_item.asc`)]);return{pedido:normOrder(order),etapas:stages.map(normStage),itens:items.map(x=>({id:x.id,idItem:x.id_item,numeroPedido:x.numero_pedido,item:x.item,manga:x.manga||'',tecido:x.tecido||'',cor:x.cor||'',qtd:Number(x.qtd||0),ordemItem:x.ordem_item,observacao:x.observacao||''})),etapaAtual:stageNow(stages.map(normStage))};}
async function authAdmin(method,path,payload){const key=env('SUPABASE_SERVICE_ROLE_KEY'),r=await fetch(`${env('SUPABASE_URL')}/auth/v1/admin/${path}`,{method,headers:sbHeaders(key),body:payload?JSON.stringify(payload):undefined}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.msg||d.message||'Erro no Supabase Auth.');return d;}
async function saveUser(p,createAuth=false){const admin=await currentUser(p.auth,'GERENCIAR_USUARIOS'),u=p.usuario||{},email=String(u.email||'').trim().toLowerCase(),profile=String(u.perfil||'').toUpperCase();if(!email||!u.nome||!['ADMIN','PCP','PRODUCAO','CONSULTA'].includes(profile))throw new Error('Dados do usuário inválidos.');let authId='';if(createAuth){if(String(u.senha||'').length<6)throw new Error('A senha deve ter pelo menos 6 caracteres.');authId=(await authAdmin('POST','users',{email,password:u.senha,email_confirm:true,user_metadata:{name:u.nome}})).id;}const data={email,nome:String(u.nome).trim(),perfil:profile,ativo:u.ativo!==false,...(authId?{auth_user_id:authId}:{})};let saved;if(u.id)saved=(await patch('usuarios_perfis',`id=${eq(u.id)}`,data))[0];else{const old=(await get('usuarios_perfis',`select=*&email=${eq(email)}&limit=1`))[0];saved=old?(await patch('usuarios_perfis',`id=${eq(old.id)}`,data))[0]:(await post('usuarios_perfis',data))[0];}await audit(admin,createAuth?'CRIAR_USUARIO_AUTH':u.id?'EDITAR_USUARIO':'CRIAR_USUARIO','usuarios_perfis',saved.id,'',null,saved);return{sucesso:true,mensagem:'Usuário salvo com sucesso.',usuario:saved,usuarios:await action('listarUsuariosSistema',[p.auth])};}
async function action(name,args){const p=args[0]||{};if(name==='loginSupabaseSistema')return login(p);if(name==='obterUsuarioLogado'){const u=await currentUser(p);return{sucesso:true,usuario:u,permissoes:permissions(u.perfil)}}if(name==='obterDadosIniciais')return initial(p);if(name==='testeConexaoSupabase'){const u=await currentUser(p);return{sucesso:true,mensagem:`Conexão OK. Usuário: ${u.nome} (${u.perfil}).`}}if(name==='analisarArquivoExcel')return analyze(p);if(name==='salvarPedido')return saveOrder(p);if(name==='obterDetalhePedidoCompleto')return detail(p);if(name==='obterEtapaAtualPedidoRapido'){const d=await detail(p),now=stageNow(d.etapas),raw=await get('pedidos_etapas',`select=*&numero_pedido=${eq(p.numeroPedido)}`),order=(await get('pedidos',`select=*&numero_pedido=${eq(p.numeroPedido)}&limit=1`))[0];return{pedido:d.pedido,etapa:now.etapaObj,card:card(order,raw)}}if(name==='salvarEtapaAtualRapido')return quickStage(p);if(name==='editarQualquerEtapaAdmin')return quickStage(p,true);if(name==='listarUsuariosSistema'){await currentUser(p,'GERENCIAR_USUARIOS');return(await get('usuarios_perfis','select=*&order=nome.asc')).map(x=>({id:x.id,authUserId:x.auth_user_id||'',email:x.email,nome:x.nome,perfil:x.perfil,ativo:Boolean(x.ativo),ultimoAcesso:x.ultimo_acesso||'',criadoEm:x.criado_em||''}))}if(name==='salvarUsuarioSistema')return saveUser(p);if(name==='criarUsuarioAuthESistema')return saveUser(p,true);if(name==='alterarSenhaUsuarioAuth'){const u=await currentUser(p.auth,'GERENCIAR_USUARIOS');if(String(p.novaSenha||'').length<6)throw new Error('Senha muito curta.');await authAdmin('PUT',`users/${p.authUserId}`,{password:p.novaSenha});await audit(u,'ALTERAR_SENHA_USUARIO','auth.users',p.authUserId,'',null,null);return{sucesso:true,mensagem:'Senha alterada.'}}if(name==='editarPedidoAdmin'){const u=await currentUser(p.auth,'EDITAR_PEDIDO'),d=p.pedido,b=(await get('pedidos',`select=*&numero_pedido=${eq(d.numeroPedido)}&limit=1`))[0],after=(await patch('pedidos',`id=${eq(b.id)}`,{cliente:d.cliente,data_entrada:brISO(d.dataEntrada),data_entrega:brISO(d.dataEntrega),prazo_original:d.prazoOriginal,qtd_total:Number(d.qtdTotal||0)}))[0];await audit(u,'EDITAR_PEDIDO','pedidos',b.id,b.numero_pedido,b,after);return{...(await initial(p.auth)),mensagem:'Pedido editado.'}}if(name==='apagarPedidoAdmin'){const u=await currentUser(p.auth,'APAGAR_PEDIDO'),b=(await get('pedidos',`select=*&numero_pedido=${eq(p.numeroPedido)}&limit=1`))[0],a=(await patch('pedidos',`id=${eq(b.id)}`,{ativo:false,status:'EXCLUÍDO',excluido_em:new Date().toISOString(),excluido_por:u.authUserId,motivo_exclusao:p.motivo}))[0];await audit(u,'EXCLUIR_PEDIDO_LOGICO','pedidos',b.id,b.numero_pedido,b,a,p.motivo);return{...(await initial(p.auth)),mensagem:'Pedido apagado.'}}throw new Error(`Operação ainda não migrada: ${name}`);}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'Método não permitido.'});try{return res.status(200).json({result:await action(req.body?.action,req.body?.args||[])});}catch(error){console.error(error);return res.status(400).json({error:error.message||'Erro interno.'});}}

